import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="grid h-full w-full grid-cols-[300px_1fr]">
        {/* Navigation */}
        <nav className="border-r border-black h-full p-4">
          <h1 className="text-3xl font-bold mb-4">Pokemon Picker</h1>
          <div>
            <h2 className="text-xl border-b border-black">Pokemon API</h2>
            <ul className="space-y-1">
              <li>
                <Link href="/" className="text-blue-600 hover:underline">Pokemon Picker</Link>
              </li>
              <li>
                <Link href="/turbo" className="text-blue-600 hover:underline">Turbo Version</Link>
              </li>
              <li>
                <Link href="/eturbo" className="text-blue-600 hover:underline">Extra Turbo Version</Link>
              </li>
              <li>
                <a href="#" className="text-blue-600 hover:underline">
                  Pokemon Battle
                </a>
              </li>
              <li>
                <a href="#" className="text-blue-600 hover:underline">
                  Battle Stats
                </a>
              </li>
            </ul>
          </div>
        </nav>
        
        {/* Main Content */}
        <div className={`${geistSans.variable} ${geistMono.variable} antialiased p-4`}>
          {children}
        </div>
      </body>
    </html>
  );
}
